dist: trusty
language: ruby
cache: bundler
env:
- RAILS_ENV=test

rvm:
  - 2.4

services:
  - postgresql

addons:
  postgresql: "9.6"

before_script:
  - cp config/database.yml.travis config/database.yml

script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rspec
