version: '2'
services:
  rails:
    build: .
    command: 'bash -c "rm -f /var/run/rails.pid && bundle exec rails s -b 0.0.0.0 --pid /var/run/rails.pid"'
    ports:
      - '3000:3000'
    environment:
      - BUNDLE_PATH=/bundle/2.6/
      - RSG_REDIS_HOST=redis
      - RSG_REDIS_PORT=6379
    volumes:
      - .:/app
      - bundler-data:/bundle
    depends_on:
      - pg
      - redis

  pg:
    image: postgres:9.6
    volumes:
      - pg-data:/var/lib/postgresql/data

  redis:
    image: redis:3.2.7-alpine
    command: 'redis-server --appendonly yes --bind 0.0.0.0'
    volumes:
      - redis-data:/data

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      - BUNDLE_PATH=/bundle/2.6/
      - RSG_REDIS_HOST=redis
      - RSG_REDIS_PORT=6379
    volumes:
      - .:/app
      - bundler-data:/bundle
    depends_on:
      - pg
      - redis

volumes:
  bundler-data:
    external:
      name: bundler_data

  redis-data:
    driver: local

  pg-data:
    driver: local
