version: '2'
services:
  rails:
    build: .
    command: 'bash -c "rm -f /var/run/rails.pid && bundle exec rails s -b 0.0.0.0 -p 80 --pid /var/run/rails.pid"'
    expose:
      - '80'
    environment:
      - BUNDLE_PATH=/bundle/2.3/
      - RAILS_ENV=$RAILS_ENV
    volumes:
      - .:/app
      - bundler-data:/bundle
    depends_on:
      - pg
    labels:
      com.dnsdock.name: "random_steam_game"
      com.dnsdock.image: ""

  pg:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=random_steam_game_$RAILS_ENV

volumes:
  bundler-data:
    external:
      name: bundler_data
