default: &default
  adapter: postgresql
  encoding: unicode
  user: <%= ENV.fetch('RSG_PG_DATABASE_USER')%>
  pool: <%= ENV.fetch('RSG_PG_POOL_SIZE')%>
  host: <%= ENV.fetch('RSG_PG_DATABASE_HOST')%>
  database: <%= ENV.fetch('RSG_PG_DATABASE_NAME')%>
  port: <%= ENV.fetch('RSG_PG_DATABASE_POST')%>

development:
  <<: *default

test:
  <<: *default
  database:  <%= ENV.fetch('RSG_PG_DATABASE_NAME_TEST')%>

production:
  <<: *default
